apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
      name: postgres
    spec:
      containers:
      - image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5433
          name: db
          protocol: TCP
