apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      containers:
      - image: redis:2.8.19
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
